name: auto-review

on:
  pull_request:
    branches:
      - main

jobs:
  auto-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Auto GPT Review
        uses: microsoft/gpt-review@v0.8.0
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          AZURE_OPENAI_API: "${{ secrets.AZURE_OPENAI_API }}"
          AZURE_OPENAI_API_KEY: "${{ secrets.AZURE_OPENAI_API_KEY }}"
